//
// indicator_helper_ispc_avx512skx.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>

#if !defined(__cplusplus)
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
#include <stdbool.h>
#else
typedef int bool;
#endif
#endif



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void calculate_atr(double * input_high, double * input_low, double * input_close, double * true_range_buff, double * output, uint64_t data_size, uint64_t window_size);
    extern void calculate_bollinger_band(double * input, double * top_output, double * sma_output, double * bottom_output, uint64_t data_size, uint64_t window_size, double standard_deviation_multiplier);
    extern void calculate_ema(double * input, double * output, uint64_t data_size, uint64_t window_size);
    extern void calculate_mcda(double * input, double * ema_period_1_buffer, double * ema_period_2_buffer, double * mcda_output, double * signal_output, double * histogram_output, uint64_t period_1, uint64_t period_2, uint64_t signal_period, uint64_t data_size);
    extern void calculate_roc(double * input, double * output, uint64_t data_size, uint64_t window_size);
    extern void calculate_rsi(double * input, double * output, uint64_t data_size, uint64_t window_size);
    extern void calculate_sma(double * input, double * output, uint64_t data_size, uint64_t window_size);
    extern void calculate_wma(double * input, double * output, uint64_t data_size, uint64_t window_size);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus
